# Generated by Django 4.2.23 on 2025-08-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmart', '0004_item_price_alter_item_description_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
